<?php /*<div class="cdz-main-menu cdz-main-menu-horizontal">
<ul class="groupmenu">

    <?php
        $obj = new Mage_Catalog_Block_Navigation();
        $storeCategories = $obj->getStoreCategories();
        Mage::registry('current_category') ? $currentCategoryId = Mage::registry('current_category')->getId() : $currentCategoryId='';
        foreach ($storeCategories as $_category):
    ?>
           <li class="level0 level-top parent">
		   <span class="cdz-menu-toggle">toggle</span>
<a class="menu-link" href="<?php echo $_category->getUrl(); ?>"><span><?php echo $_category->getName(); ?></span></a>
		   <div class="groupmenu-drop">
<div class="groupmenu-drop-content groupmenu-6" style="padding-bottom: 60px;">
<div class="row">
                
                <?php $categoryChildren = $_category->getChildren(); ?>
                <?php if($categoryChildren->count()) : ?>
                    
 <div class="col-sm-4">
                        <?php foreach($categoryChildren as $_categoryChild) : ?>
                            <?php $_categoryChildModel = Mage::getModel('catalog/category')->load($_categoryChild->getId());?>
							<div class="groupdrop-banner space-s">
							<img  src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' .Mage::getModel('catalog/category')->load($_categoryChild->getId())->getThumbnail();?>"/>
							</div>
							
							
                            <?php $categoryGrandchildren=$_categoryChild->getChildren(); ?>
                           
                          <?php
						  $currentCategoryId===$_categoryChild->getId() ? $bold="style=\"font-weight:bold\"" : $bold='';
                             echo  '<a href="' . $_categoryChildModel->getUrl() . '"' . $bold . '>' .  $_categoryChild->getName() .'</a>';
                              ?>
                      

							   
                            </li>
                            <?php if($categoryGrandchildren->count()) : ?>
                                <?php foreach($categoryGrandchildren as $_categoryGrandchild) : ?>
                                    <?php $_categoryGrandchildModel = Mage::getModel('catalog/category')->load($_categoryGrandchild->getId());?>
                                   
                                        <?php
                                            $currentCategoryId===$_categoryChild->getId() ? $bold="style=\"font-weight:bold\"" : $bold='';
                                            echo '&emsp;&emsp;' . '<a href="' . $_categoryGrandchildModel->getUrl() . '"' . $bold . '>' .  $_categoryGrandchild->getName() . '(' . $_categoryGrandchildModel->getProductCount() . ')</a>';
                                        ?>
                                   
                                <?php endforeach; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                   
                <?php endif; ?>
           
        <?php endforeach ?>
		</div><!--row div-->
</div>
</div> 
</ul>
</div>

*/?>


<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<?php $currentCategory = Mage::registry('current_category') ?>
<?php if (count($_categories) > 0): ?>
    <ul>
        <?php foreach($_categories as $_category): ?>
            <li>
                <a href="<?php echo $_helper->getCategoryUrl($_category) ?>">
                    <?php echo $_category->getName() ?>
                </a>
                <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                <?php $_subcategories = $_category->getChildrenCategories() ?>
                <?php if (count($_subcategories) > 0): ?>
                    <ul>
                        <?php foreach($_subcategories as $_subcategory): ?>
                            <li>
                          <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">
                         <?php echo $_subcategory->getName().$_subcategory->getId(); ?>
                                </a>
						 <?php $_subsubcategory = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>
								<?php if (count($_subsubcategory) > 0): ?>
								 <?php foreach($_subsubcategory as $_subcategory1): ?>
								 <?php  echo '3rd level--'. $_subcategory1->getName(); ?>
								<?php endforeach; ?>
								<?php endif;?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>