<div class="cdz-main-menu cdz-main-menu-horizontal">

<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<?php $currentCategory = Mage::registry('current_category') ?>
<?php if (count($_categories) > 0): ?>
  <ul class="groupmenu">
        <?php foreach($_categories as $_category): ?>
           <li class="level0 level-top parent">
		   <span class="cdz-menu-toggle">toggle</span>
		   <a class="menu-link" href="<?php echo $_helper->getCategoryUrl($_category) ?>">
			<span><?php echo $_category->getName() ?></span>
			</a>
                <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                <?php $_subcategories = $_category->getChildrenCategories() ?>
                <?php if (count($_subcategories) > 0): ?>
<div class="groupmenu-drop">
				 
                <div class="groupmenu-drop-content groupmenu-6" style="padding-bottom: 60px;">
						<div class="row">
                        <?php foreach($_subcategories as $_subcategory): ?>
						<div class="col-sm-4">
						<div class="groupdrop-banner space-s">
						<?php if(Mage::getModel('catalog/category')->load($_subcategory->getId())->getThumbnail()!=''){?>
						<img  width="200px" height="200px" class="img-responsive" src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' .Mage::getModel('catalog/category')->load($_subcategory->getId())->getThumbnail();?>"/>
						<?php }?>
					</div>
                       <p class="groupdrop-title">
                            <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">                                    <?php echo $_subcategory->getName() ?>
                             </a>
							 </p>

							<?php  $_subsubcategory = Mage::getModel('catalog/category')->load($_subcategory->getId());
		 
							 $_subsubcategories = $_subsubcategory->getChildrenCategories() ;	?>
							 <?php if (count($_subcategories) > 0): ?>
							 <ul class="groupdrop-link">
							 <?php foreach($_subsubcategories as $_subsubcategory){?>
							 <li class="item"><a href="<?php echo $_helper->getCategoryUrl($_subsubcategory) ?>">
							<?php echo  $_subsubcategory->getName();?></a></li>
							 <?php }?>
							 </ul>
							 <?php endif; ?>

							
						</div>
                        <?php endforeach; ?>
						
                    </div>
				</div>
				</div> <!--row div-->
                <?php endif; ?>
				
				
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>