<div class="cdz-main-menu cdz-main-menu-horizontal">

<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<?php $currentCategory = Mage::registry('current_category') ?>
<?php if (count($_categories) > 0): ?>
  <ul class="groupmenu">
        <?php foreach($_categories as $_category): ?>
           <li class="level0 level-top parent">
		   <span class="cdz-menu-toggle">toggle</span>
		       <?php   
               if($_category->getId()==166)
			   {		   
			   $bold="background:#f54444" ;
			   }
			   else{$bold="";}
               ?>
		   <a class="menu-link"  style="<?php echo $bold; ?>" href="<?php echo $_helper->getCategoryUrl($_category) ?>">
			<span><?php echo $_category->getName() ?></span>
			</a>
                <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                <?php $_subcategories = $_category->getChildrenCategories() ?>
                <?php if ((count($_subcategories)>0 )and
				(count($_subcategories)<=2)){
					echo 'arv'.count($_subcategories);
					?>
                <div class="groupmenu-drop">				 
               <div class="groupmenu-drop-content groupmenu-1">
						<div class="row"> <!--row div-->
                        <?php foreach($_subcategories as $_subcategory): ?>
						<div class="col-sm-24"><!--single level-->
						<div class="groupdrop-banner space-s">
						<?php if(Mage::getModel('catalog/category')->load($_subcategory->getId())->getThumbnail()!=''){?>
						<img  width="200px" height="200px" class="img-responsive" src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' .Mage::getModel('catalog/category')->load($_subcategory->getId())->getThumbnail();?>"/>
						<?php }?>
					</div>
                       <ul class="groupdrop-link">
                            <li class="item"><a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">                                    <?php echo $_subcategory->getName() ?>
                             </a></li>
					   </ul>
					   <!--second level for 2 coloumn-->
					   <?php  $_subsubcategory = Mage::getModel('catalog/category')->load($_subcategory->getId());
		 
							 $_subsubcategories = $_subsubcategory->getChildrenCategories() ;	?>
							 <?php  if (count($_subcategories) > 0): ?>
							 <ul class="groupdrop-link">
							 <?php foreach($_subsubcategories as $_subsubcategory){?>
							 <li class="item"><a href="<?php echo $_helper->getCategoryUrl($_subsubcategory) ?>">
							<?php echo  $_subsubcategory->getName();?></a></li>
							 <?php }?>
							 </ul>
							 <?php endif; ?>
					   

							 <!--second level for 2 coloumn end -->
						
                    </div>
					<?php endforeach; ?>
				</div><!--row div-->
				</div> 
				<?php }else{?>	
           <?php if (count($_subcategories)>0 ){
			   ?> 			
					<div class="groupmenu-drop">				 
                <div class="groupmenu-drop-content groupmenu-6" style="padding-bottom: 60px;">
						<div class="row"> <!--row div-->
                        <?php foreach($_subcategories as $_subcategory): ?>
						<div class="col-sm-4">
						<div class="groupdrop-banner space-s">
						<?php if(Mage::getModel('catalog/category')->load($_subcategory->getId())->getThumbnail()!=''){?>
						<img  width="200px" height="200px" class="img-responsive" src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' .Mage::getModel('catalog/category')->load($_subcategory->getId())->getThumbnail();?>"/>
						<?php }?>
					</div>
                       <p class="groupdrop-title">
                            <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">                                    <?php echo $_subcategory->getName() ?>
                             </a>
							 </p>

							<?php  $_subsubcategory = Mage::getModel('catalog/category')->load($_subcategory->getId());
		 
							 $_subsubcategories = $_subsubcategory->getChildrenCategories() ;	?>
							 <?php  echo "abc".count($_subcategories);if (count($_subcategories) > 0): ?>
							 <ul class="groupdrop-link">
							 <?php foreach($_subsubcategories as $_subsubcategory){?>
							 <li class="item"><a href="<?php echo $_helper->getCategoryUrl($_subsubcategory) ?>">
							<?php echo  $_subsubcategory->getName();?></a></li>
							 <?php }?>
							 </ul>
							 <?php endif; ?>

							
						</div>
                        <?php endforeach; ?>
						
                    </div><!--row div-->
				</div>
				</div>
					
				<?php }}?>
				
				
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>