<?php if (!$methods = $this->getMethods()) : ?>
<p><?php echo $this->helper('checkout')->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else : ?>
<dl class="sp-methods">
<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode();  

//echo "Checking...".

$disableCod = false;
if($_code=='cashondelivery'){
    $quote = Mage::getSingleton('checkout/cart')->getQuote();
    $subTotal = $quote->getSubtotal();
    //echo "Total:".$subTotal;
    $codLimit = Mage::getModel('core/variable')->loadByCode('cod_limit')->getValue('plain');
    if($subTotal>trim($codLimit)){
        echo "This product is not eligible for COD.";
        $disableCod = true;

     }
    } // disble COD 
    
    if($disableCod == false):
    ?>
    <dt>
    <?php if( sizeof($this->getMethods()) > 1 ): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
    <?php else: ?>
        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->htmlEscape($_method->getTitle()) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </dt>
    <?php 
    endif; 
    ?>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
   <!--  <dd>
        <?php echo $html; ?>
    </dd> -->
    <?php endif; ?>
<?php endforeach; ?>
</dl>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
payment.init();
//]]>
</script>
<?php endif; ?>
